return allowed origin for every method
prest/middlewares pull request #11
Opened 2017-12-08 15:55 UTC by tiaguinho

Without this change, prest can't return headers properly for requests when cors is enabled.
I made some tests using Angular 5.1.0. When prest doesn't add origin to the header, I receive an error that Access-Control-Allow-Origin isn't present on response header.

ping @crgimenes @felipeweb @avelino

2017-12-08 16:06 UTC, brunomaomeh commented
@sebastianwebber and I had this same problem yesterday. thanks for commit

2017-12-08 16:07 UTC, felipeweb approved these changes

2017-12-08 16:39 UTC, sebastianwebber requested changes

2017-12-08 16:39 UTC, sebastianwebber commented on middlewares.go
>  			w.Header().Set(headerAllowCredentials, strconv.FormatBool(true))
On our VueJS app the `headerAllowCredentials` is also missing.

Can you add this header too?

2017-12-08 16:40 UTC, brunomaomeh commented
I pulled the project, but I still with this error:
_"The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'."_

to fix this, I just put the _Access-Control-Allow-Credentials_ header together with _Access-Control-Allow-Origin_ (outside from the _if r.Method == "OPTIONS"_ ... )

2017-12-08 23:09 UTC, tiaguinho commented
@sebastianwebber I just added.
Thanks.

2017-12-09 00:27 UTC, sebastianwebber approved these changes
LGTM

2017-12-09 09:20 UTC, crgimenes approved these changes
LGTM

2017-12-09 09:20 UTC, merged

2017-12-09 09:21 UTC, crgimenes commented
Thank you for your help!