Move the statements package into the middlewares package
prest/middlewares pull request #15
Opened 2018-10-01 10:52 UTC by joelmdesouza

As in the adapaters package we moved the statements into it, I moved the statements concerning the middlewares into it.

@felipeweb @avelino @crgimenes @lerrua @cassiobotaro

2019-01-14 09:58 UTC, crgimenes approved these changes
LGTM

2019-01-14 12:34 UTC, felipeweb approved these changes

2019-01-14 12:43 UTC, joelmdesouza commented
If the merge fails, it is due to the expiration of the JWT token used in the test.

2019-01-14 13:36 UTC, marioidival approved these changes
LGTM

2019-01-14 19:54 UTC, felipeweb commented
@joelmdesouza  could you generate a token that never expires for test proposals in http://jwt.io

2019-01-14 19:55 UTC, felipeweb requested changes

2019-01-14 19:55 UTC, felipeweb commented on config_test.go
> +	bearer := "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQHNvbWV3aGVyZS5jb20iLCJleHAiOjE1NDI2NzIwMDAsImlhdCI6MTUxNzU2MzYxNiwiaXNzIjoicHJpdmF0ZSIsImp0aSI6ImNlZmE3NGZlLTg5NGMtZmY
use JWT that never expires

2019-01-15 10:06 UTC, joelmdesouza commented on config_test.go
> +	bearer := "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQHNvbWV3aGVyZS5jb20iLCJleHAiOjE1NDI2NzIwMDAsImlhdCI6MTUxNzU2MzYxNiwiaXNzIjoicHJpdmF0ZSIsImp0aSI6ImNlZmE3NGZlLTg5NGMtZmY
Done

2019-01-15 10:48 UTC, avelino approved these changes

2019-01-15 11:51 UTC, merged